// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'portfolio';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ATTENDANCE = 'assets/icons/attendance.png';
  static const String CALL = 'assets/icons/call.png';
  static const String DELIVERY = 'assets/icons/delivery.png';
  static const String DESIGN = 'assets/icons/design.png';
  static const String GITHUB = 'assets/icons/github.png';
  static const String INSTA = 'assets/icons/insta.png';
  static const String LOCATION = 'assets/icons/location.png';
  static const String MAIL = 'assets/icons/mail.png';
  static const String OPENSOURCE = 'assets/icons/opensource.png';
  static const String SMARTPHONE = 'assets/icons/smartphone.png';
  static const String TECNICALWRITING = 'assets/icons/tecnicalWriting.png';
  static const String WEATHERAPP = 'assets/icons/weatherapp.png';
  static const String XICON = 'assets/icons/xicon.png';
  static const String YOUTUBEICON = 'assets/icons/youtubeicon.png';
  static const String ABOUT = 'assets/images/about.png';
  static const String ABOUTMOBILEFINAL = 'assets/images/aboutmobilefinal.png';
  static const String BAT = 'assets/images/bat.png';
  static const String HOME = 'assets/images/home.jpeg';
  static const String HOME = 'assets/images/home.jpg';
  static const String HOME = 'assets/images/home.png';
  static const String HOMEPICTURE = 'assets/images/homepicture.png';
  static const String LOADING = 'assets/loading.json';
}
